[container]
image = "reitzig/texlive-base-luatex"
os_flavor = "alpine"

name = "container-do-latex-example"
work_dir = "/work/tmp"

mounts = [
    ".:/work/src:ro"
]
keep_alive = "15m"

[run.setup]
attach = true
commands = [
    "tlmgr update --self",
    "eval 'xargs tlmgr install < /work/src/Texlivefile'"
]

[run.before]
commands = [
    "rm -f *.pdf *.log",
    "cp -rf /work/src/* ./"
]

[[copy.after]]
files = ["*.pdf", "*.log"]
to = "out"
