[container]
image = "maven:3-jdk-11-slim"
os_flavor = "debian"

name = "container-do-java-example"
work_dir = "/app"

[container.environment]
MAVEN_OPTS = "$MAVEN_OPTS"

[run.setup]
attach = true
commands    = [
    "mvn dependency:resolve"
]
